### ISSUE TITLE
Updated version

### ISSUE THREAD

**Issue by habernal** [ShawnZhong/PyTorchDoc#1]
Hello, is there a way to re-run compilation of this single-html API page? Or was it a manual effort?

**Comment by ShawnZhong** [comment]
You can run `make singlehtml` in the [`docs` folder](https://github.com/pytorch/pytorch/tree/master/docs) to get the single-page HTML file at `docs/build/singlehtml/index.html`.

**Comment by habernal** [comment]
Great, thanks!
